import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./nav/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextJS POC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <h2
          style={{
            textAlign: "center",
            fontWeight: "bold",
            backgroundColor: "#f2f2f2",
            paddingBottom: "6px",
          }}
        >
          NextJS App
        </h2>
        <Nav />
        {children}
      </body>
    </html>
  );
}
